services:
    App\Console\:
        resource: '%kernel.project_dir%/src/Console/'
        autoconfigure: true
        bind:
            $controllerEmulator: '@App\Http\FakeController'
            $schemaIdMapper: '@App\MessengerIntegration\Message\SchemaIdMapperInterface'
