services:
    App\Console\:
        resource: '%kernel.project_dir%/src/Console/'
        autoconfigure: true
        bind:
            $serializer: '@App\MessengerIntegration\Serializer\IntegrationSerializer'
            $controllerEmulator: '@App\Http\FakeController'
