services:
    App\Http\FakeController:
        arguments:
            $logger: '@monolog.logger.application'
            $inputInboxService: '@App\MessengerIntegration\Inbox\InputInboxService'
            $schemaIdMapper: '@App\MessengerIntegration\Message\SchemaIdMapperInterface'
