services:
    App\Http\FakeController:
        arguments:
            $logger: '@monolog.logger.application'
            $inputInboxService: '@App\MessengerIntegration\Inbox\InputInboxService'
            $messageAttributeStorage: '@App\MessengerIntegration\Message\IntegrationMessageAttributeStorage'
