services:

    App\MessengerIntegration\Serializer\IntegrationSerializer:
        arguments:
            $schemaIdMapper: '@App\MessengerIntegration\Mapper\SchemaIdMapperInterface'
            $bodySerializer: '@App\MessengerIntegration\Serializer\Body\BodySerializerInterface'
            $messengerStampsSerializer: '@App\MessengerIntegration\Serializer\MessengerStamps\MessengerStampsSerializerInterface'
            $integrationStampsSerializer: '@App\MessengerIntegration\Serializer\IntegrationStamps\IntegrationStampsSerializerInterface'
            $logger: '@monolog.logger.integration'

    App\MessengerIntegration\Serializer\Body\BodySerializerInterface:
        alias: App\MessengerIntegration\Serializer\Body\JsonMessageBodySerializer

    App\MessengerIntegration\Serializer\Body\JsonMessageBodySerializer:


    App\MessengerIntegration\Serializer\IntegrationStamps\IntegrationStampsSerializerInterface:
        alias: App\MessengerIntegration\Serializer\IntegrationStamps\IntegrationStampsSerializer

    App\MessengerIntegration\Serializer\IntegrationStamps\IntegrationStampsSerializer:

    App\MessengerIntegration\Serializer\MessengerStamps\MessengerStampsSerializerInterface:
        alias: App\MessengerIntegration\Serializer\MessengerStamps\MessengerStampsSerializer

    App\MessengerIntegration\Serializer\MessengerStamps\MessengerStampsSerializer:
        arguments:
            $symfonySerializer: '@serializer'

    App\MessengerIntegration\Mapper\SchemaIdMapperInterface:
        alias: App\MessengerIntegration\Mapper\InMemorySchemaIdMapper

    App\MessengerIntegration\Mapper\InMemorySchemaIdMapper:
        arguments:
            $list:
                'mm.dev.test': 'App\Message\TestMessage'

    App\MessengerIntegration\Middleware\TestMiddleware:
        arguments:
            $logger: '@monolog.logger.integration'

    App\MessengerIntegration\Transport\Amqp\IntegrationAmqpTransportFactory:
        tags:
            - { name: 'messenger.transport_factory' }
