framework:
    messenger:

        buses:
            application_bus:
#                default_middleware:
#                    enabled: true
#                    allow_no_handlers: true
#                    allow_no_senders: false
                middleware:
                    - 'App\MessengerIntegration\Middleware\InboxRouterMiddleware'
                    - 'App\MessengerIntegration\Middleware\OutboxRouterMiddleware'
                    - 'App\MessengerIntegration\Middleware\OutgoingHttpRouterMiddleware'
                    - 'App\MessengerIntegration\Middleware\OutgoingKafkaRouterMiddleware'

        default_bus: application_bus

        failure_transport: failed_transport

        transports:

            failed_transport:
                dsn: 'doctrine://application'
                serializer: 'messenger.default_serializer'
                retry_strategy:
                    max_retries: 100000
                options:
                    table_name: 'demo.messenger_messages'
                    queue_name: 'failed'
                    auto_setup: true

            inbox_transport:
                dsn: 'doctrine://application'
                serializer: 'messenger.default_serializer'
                options:
                    table_name: 'demo.messenger_messages'
                    queue_name: 'inbox'
                    auto_setup: true
                retry_strategy:
                    max_retries: 0

            outbox_transport:
                dsn: 'doctrine://application'
                serializer: 'messenger.default_serializer'
                options:
                    table_name: 'demo.messenger_messages'
                    queue_name: 'outbox'
                    auto_setup: true
                retry_strategy:
                    max_retries: 1
                    delay: 2000

            http_publisher_transport:
                dsn: 'integration-http://'
                serializer: 'messenger.default_serializer'

            kafka_publisher_transport:
                dsn: 'integration-kafka://'
                serializer: 'messenger.default_serializer'

