framework:
    messenger:

        buses:
            application_bus:
#                default_middleware:
#                    enabled: true
#                    allow_no_handlers: true
#                    allow_no_senders: false
                middleware:
                    - 'App\MessengerIntegration\Middleware\InboxRouterMiddleware'
                    - 'App\MessengerIntegration\Middleware\OutboxRouterMiddleware'
                    - 'App\MessengerIntegration\Middleware\OutgoingHttpRouterMiddleware'
                    - 'App\MessengerIntegration\Middleware\OutgoingKafkaRouterMiddleware'

        default_bus: application_bus

        failure_transport: failed_transport

        transports:

            failed_transport:
                dsn: 'doctrine://application'
                serializer: 'messenger.default_serializer'
                retry_strategy:
                    max_retries: 100000
                options:
                    table_name: 'demo.messenger_messages'
                    queue_name: 'failed'
                    auto_setup: true

            inbox_transport:
                dsn: 'doctrine://application'
                serializer: 'messenger.default_serializer'
                options:
                    table_name: 'demo.messenger_messages'
                    queue_name: 'inbox'
                    auto_setup: true
                retry_strategy:
                    max_retries: 0

            outbox_transport:
                dsn: 'doctrine://application'
                serializer: 'messenger.default_serializer'
                options:
                    table_name: 'demo.messenger_messages'
                    queue_name: 'outbox'
                    auto_setup: true
                retry_strategy:
                    max_retries: 1
                    delay: 2000

            http_publisher_transport:
                dsn: 'integration-http://'
                serializer: 'messenger.default_serializer'

            kafka_publisher_transport:
                dsn: 'integration-kafka://'
                serializer: 'messenger.default_serializer'


#            app_doctrine_transport:
#                dsn: 'doctrine://application'
#                options:
#                    table_name: 'demo.messenger_messages'
#                    queue_name: 'application'
#                    auto_setup: true
#                retry_strategy:
#                    max_retries: 0
#                    delay: 1000
#                    multiplier: 1
#
#            app_amqp_transport:
#                dsn: '%env(APP_AMQP_DSN)%'
#                serializer: 'App\MessengerIntegration\Serializer\IntegrationSerializer'
#                options:
#                    heartbeat: 30
#                    confirm_timeout: 5
#                    queues:
#                        app_transport_queue:
#                            binding_keys:
#                                - '#'
#                    exchange:
#                        name: 'app_transport_exchange'
#                        type: topic
#                    auto_setup: true
#                retry_strategy:
#                    max_retries: 1
#                    delay: 2000
#                    multiplier: 1
#
#            app_kafka_producer:
#                dsn: 'kafka://'
#                options:
#                    flushTimeout: 1000
#                    flushRetries: 1
#                    topic:
#                        name: 'app_transport_topic'
#                    kafka_conf:
#                        'bootstrap.servers': '%env(APP_KAFKA_BOOTSTRAP_SERVERS)%'
#                        'security.protocol': 'plaintext'
#
#            app_kafka_consumer:
#                dsn: 'kafka://'
#                options:
#                    commitAssync: 'true'
#                    receiveTimeout: 2000
#                    topic:
#                        name: 'app_transport_topic'
#                    kafka_conf:
#                        'bootstrap.servers': '%env(APP_KAFKA_BOOTSTRAP_SERVERS)%'
#                        'security.protocol': 'plaintext'
#                        'enable.auto.offset.store': 'false'
##                            'enable.auto.commit': 'false'
#                        'group.id': '%env(APP_KAFKA_CONSUMER_GROUP_ID)%'
#                    topic_conf:
#                        'auto.offset.reset': 'earliest'
#                retry_strategy:
#                    max_retries: 0
