framework:
    messenger:

        buses:
            app_default_bus:
            app_sync_bus:

        default_bus: app_default_bus

        transports:

            app_failed_transport:
                dsn: 'doctrine://application'
                retry_strategy:
                    max_retries: 0
                options:
                    table_name: 'demo.messenger_messages'
                    queue_name: 'failed'
                    auto_setup: true

            app_doctrine_transport:
                dsn: 'doctrine://application'
                options:
                    table_name: 'demo.messenger_messages'
                    queue_name: 'application'
                    auto_setup: true
                retry_strategy:
                    max_retries: 0
                    delay: 1000
                    multiplier: 1

            app_amqp_transport:
                dsn: '%env(APP_AMQP_DSN)%'
                options:
                    confirm_timeout: 5
                    queues:
                        app_transport_queue:
                            binding_keys:
                                - '#'
                    exchange:
                        name: 'app_transport_exchange'
                        type: topic
                    auto_setup: true
                retry_strategy:
                    max_retries: 0
                    delay: 1000
                    multiplier: 1

            app_kafka_producer:
                dsn: 'kafka://'
                options:
                    flushTimeout: 1000
                    flushRetries: 1
                    topic:
                        name: 'app_transport_topic'
                    kafka_conf:
                        'bootstrap.servers': '%env(APP_KAFKA_BOOTSTRAP_SERVERS)%'
                        'security.protocol': 'plaintext'

            app_kafka_consumer:
                dsn: 'kafka://'
                options:
                    commitAssync: 'true'
                    receiveTimeout: 2000
                    topic:
                        name: 'app_transport_topic'
                    kafka_conf:
                        'bootstrap.servers': '%env(APP_KAFKA_BOOTSTRAP_SERVERS)%'
                        'security.protocol': 'plaintext'
                        'enable.auto.offset.store': 'false'
#                            'enable.auto.commit': 'false'
                        'group.id': '%env(APP_KAFKA_CONSUMER_GROUP_ID)%'
                    topic_conf:
                        'auto.offset.reset': 'earliest'
                retry_strategy:
                    max_retries: 0
