<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20241005151527 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create messenger_messages table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<FINISH
create function notify_messenger_messages() returns trigger
    language plpgsql
as
$$
    BEGIN
        PERFORM pg_notify('demo.messenger_messages', NEW.queue_name::text);
        RETURN NEW;
    END;
$$;
FINISH
        );
        $this->addSql('alter function notify_messenger_messages() owner to demo;');

        $this->addSql(<<<FINISH
            create table messenger_messages
            (
                id           bigint generated by default as identity primary key,
                body         text         not null,
                headers      text         not null,
                queue_name   varchar(190) not null,
                created_at   timestamp(0) not null,
                available_at timestamp(0) not null,
                delivered_at timestamp(0) default NULL::timestamp without time zone
            );
FINISH
        );

        $this->addSql('alter table messenger_messages owner to demo;');
        $this->addSql('create index idx_44e049d2fb7336f0 on messenger_messages (queue_name);');
        $this->addSql('create index idx_44e049d2e3bd61ce on messenger_messages (available_at);');
        $this->addSql('create index idx_44e049d216ba31db on messenger_messages (delivered_at);');
        $this->addSql(<<<FINISH
            create trigger notify_trigger
            after insert or update
            on messenger_messages
            for each row
            execute procedure notify_messenger_messages();
FINISH
        );
     }

    public function down(Schema $schema): void
    {
        // so...
    }
}
