parameters:

services:
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\SymfonyCommand\:
        resource: '../src/SymfonyCommand'
        tags: ['console.command']
        bind:
            $commandBus: '@command.bus'

    App\CommandHandler\:
        resource: '../src/CommandHandler/*'
        tags:
            - { name: messenger.message_handler, bus: command.bus}
